[package]
name = "testrunner"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"] }
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
walkdir = "2.5.0"
serde_json = "1.0.142"
